; Generated by go run ./cmd/genkeywords; do not edit.
; Original structural rules and token classifications: queries/*.scm, queries/tokens.json.
; MIT upstream sources used:
; tree-sitter/tree-sitter-javascript@v0.25.0/queries/highlights.scm
; tree-sitter/tree-sitter-javascript@v0.25.0/queries/highlights-jsx.scm
;   Copyright (c) 2014 Max Brunsfeld; licenses/tree-sitter-javascript/LICENSE
; zed-industries/tree-sitter-typescript@e2c53597d6a5/queries/highlights.scm
;   Copyright (c) 2017 Max Brunsfeld; licenses/tree-sitter-typescript/LICENSE
; Original additions are covered by this repository's LICENSE.

; Anonymous tokens, in lexical order; provenance: pinned node-types.json.
"!" @operator
"!=" @operator
"!==" @operator
"%" @operator
"%=" @operator
"&" @operator
"&&" @operator
"&&=" @operator
"&=" @operator
"(" @punctuation.bracket
")" @punctuation.bracket
"*" @operator
"**" @operator
"**=" @operator
"*=" @operator
"+" @operator
"++" @operator
"+=" @operator
"," @punctuation.delimiter
"-" @operator
"--" @operator
"-=" @operator
"." @punctuation.delimiter
"..." @operator
"/" @operator
"/=" @operator
":" @punctuation.delimiter
";" @punctuation.delimiter
"<" @operator
"<<" @operator
"<<=" @operator
"<=" @operator
"=" @operator
"==" @operator
"===" @operator
"=>" @operator
">" @operator
">=" @operator
">>" @operator
">>=" @operator
">>>" @operator
">>>=" @operator
"?" @operator
"?." @punctuation.delimiter
"??" @operator
"??=" @operator
"@" @punctuation.special
"[" @punctuation.bracket
"]" @punctuation.bracket
"^" @operator
"^=" @operator
"abstract" @keyword
"accessor" @keyword
"as" @keyword
"assert" @keyword
"asserts" @keyword
"async" @keyword
"await" @keyword.control
"break" @keyword.control
"case" @keyword.control
"catch" @keyword.control
"class" @keyword.declaration
"const" @keyword.declaration
"continue" @keyword.control
"debugger" @keyword.control
"declare" @keyword.declaration
"default" @keyword.control
"delete" @keyword
"do" @keyword.control
"else" @keyword.control
"enum" @keyword.declaration
"export" @keyword.import
"extends" @keyword
"finally" @keyword.control
"for" @keyword.control
"from" @keyword.import
"function" @keyword.declaration
"get" @keyword
"global" @keyword
"if" @keyword.control
"implements" @keyword
"import" @keyword.import
"in" @keyword
"infer" @keyword
"instanceof" @keyword
"interface" @keyword.declaration
"is" @keyword
"keyof" @keyword
"let" @keyword.declaration
"module" @keyword.declaration
"namespace" @keyword.declaration
"new" @keyword
"of" @keyword
"override" @keyword
"private" @keyword
"protected" @keyword
"public" @keyword
"readonly" @keyword
"require" @keyword
"return" @keyword.control
"satisfies" @keyword
"set" @keyword
"static" @keyword
"switch" @keyword.control
"throw" @keyword.control
"try" @keyword.control
"type" @keyword.declaration
"typeof" @keyword
"using" @keyword.declaration
"var" @keyword.declaration
"while" @keyword.control
"with" @keyword.control
"yield" @keyword.control
"{" @punctuation.bracket
"{|" @punctuation.bracket
"|" @operator
"|=" @operator
"||" @operator
"||=" @operator
"|}" @punctuation.bracket
"}" @punctuation.bracket
"~" @operator

; Common structural rules. Rule IDs are mapped to sources in README.md.

; C01-C09: MIT tree-sitter-javascript queries/highlights.scm, function rules.
(function_expression name: (identifier) @function)
(function_declaration name: (identifier) @function)
(method_definition name: (property_identifier) @function.method)
(pair key: (property_identifier) @function.method value: [(function_expression) (arrow_function)])
(assignment_expression left: (member_expression property: (property_identifier) @function.method) right: [(function_expression) (arrow_function)])
(variable_declarator name: (identifier) @function value: [(function_expression) (arrow_function)])
(assignment_expression left: (identifier) @function right: [(function_expression) (arrow_function)])
(call_expression function: (identifier) @function)
(call_expression function: (member_expression property: (property_identifier) @function.method))

; C10-C13: grammar-derived generator functions and private methods.
(generator_function name: (identifier) @function)
(generator_function_declaration name: (identifier) @function)
(method_definition name: (private_property_identifier) @function.method)
(call_expression function: (member_expression property: (private_property_identifier) @function.method))

; C14-C15: MIT tree-sitter-javascript queries/highlights.scm, base identifiers.
(identifier) @variable
(property_identifier) @property

; C16-C20: grammar-derived shorthand, private and declared properties.
[(shorthand_property_identifier) (shorthand_property_identifier_pattern)] @variable
(private_property_identifier) @property
(pair key: (property_identifier) @property.name)
(pair_pattern key: (property_identifier) @property.name)
(public_field_definition name: [(property_identifier) (private_property_identifier)] @property.name)

; C21-C23: grammar-derived constructor positions.
(new_expression constructor: (identifier) @constructor)
(new_expression constructor: (member_expression property: (property_identifier) @constructor))
((method_definition name: (property_identifier) @constructor) (#eq? @constructor "constructor"))
; C24-C26: MIT highlights.scm adapted constant predicate, special variables and nulls.
([(identifier) (shorthand_property_identifier) (shorthand_property_identifier_pattern)] @constant
  (#match? @constant "^[A-Z][A-Z0-9_]*$"))
[(this) (super) (meta_property)] @variable.special
[(null) (undefined)] @constant.builtin

; C27-C29: grammar-derived parameter positions, including rest bindings.
(arrow_function parameter: (identifier) @variable.parameter)
(catch_clause parameter: (identifier) @variable.parameter)
(required_parameter (rest_pattern (identifier) @variable.parameter))

; C30-C31: grammar-derived decorators and unary void.
(decorator (identifier) @function)
(unary_expression operator: "void" @keyword)

; C32-C35: MIT tree-sitter-javascript queries/highlights.scm, literals and templates.
(comment) @comment
[(string) (template_string)] @string
(number) @number
(template_substitution "${" @punctuation.special "}" @punctuation.special) @embedded

; C36, C38: MIT highlights.scm adapted literal captures; C37, C39-C40: grammar-derived.
[(true) (false)] @boolean
(escape_sequence) @string.escape
(regex) @string.regex
(regex_flags) @keyword.operator.regex
(hash_bang_line) @comment

; TypeScript structural rules; also used for JS because sema uses the TSX parser.

; T01-T03: MIT tree-sitter-typescript queries/highlights.scm.
(type_identifier) @type
(predefined_type) @type.builtin
(type_arguments "<" @punctuation.bracket ">" @punctuation.bracket)

; T04-T05: grammar-derived binding fields exclude default-value expressions.
[(required_parameter pattern: (identifier) @variable.parameter)
 (required_parameter name: (identifier) @variable.parameter)]
[(optional_parameter pattern: (identifier) @variable.parameter)
 (optional_parameter name: (identifier) @variable.parameter)]

; T06-T09: grammar-derived names in signatures and field declarations.
(function_signature name: (identifier) @function)
(method_signature name: [(property_identifier) (private_property_identifier)] @function.method)
(abstract_method_signature name: [(property_identifier) (private_property_identifier)] @function.method)
(property_signature name: [(property_identifier) (private_property_identifier)] @property.name)

; T10-T16: grammar-derived class, type, enum and namespace declarations.
(class name: (type_identifier) @type.class)
(class_declaration name: (type_identifier) @type.class)
(abstract_class_declaration name: (type_identifier) @type.class)
[(type_alias_declaration name: (type_identifier) @type.name)
 (interface_declaration name: (type_identifier) @type.name)
 (enum_declaration name: (identifier) @type.name)]
(type_parameter name: (type_identifier) @type.name)
(enum_assignment name: (property_identifier) @constant)
(internal_module name: [(identifier) (nested_identifier)] @nested)

; T17-T20: grammar-derived type delimiters, mapped modifiers and template types.
(type_parameters "<" @punctuation.bracket ">" @punctuation.bracket)
["+?:" "-?:" "?:"] @operator
(template_literal_type) @string
(template_type "${" @punctuation.special "}" @punctuation.special) @embedded

; T21: grammar-derived index-signature binding (not its index or value type).
(index_signature name: (identifier) @variable.parameter)

; T22-T26: grammar-derived type-only imports.
; import_specifier.name is the exported name; alias, when present, is the local binding.
; Both identifier names denote types, while a quoted export name remains a string.
(import_statement "type" (import_clause (named_imports (import_specifier (identifier) @type))))
(import_specifier "type" (identifier) @type)
(import_statement "type" (import_clause (identifier) @type))
(import_statement "type" (import_clause (namespace_import (identifier) @type)))
(import_statement "type" (import_require_clause (identifier) @type))

; T27: grammar-derived shorthand parameter bindings, at most 4 pattern nodes.
(required_parameter pattern: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))
(optional_parameter pattern: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))
(required_parameter pattern: (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))
(optional_parameter pattern: (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))
(required_parameter pattern: (object_pattern (object_assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(optional_parameter pattern: (object_pattern (object_assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(required_parameter pattern: (object_pattern (object_assignment_pattern left: (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (object_pattern (object_assignment_pattern left: (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (object_pattern (object_assignment_pattern left: (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (object_pattern (object_assignment_pattern left: (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (object_pattern (pair_pattern value: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(optional_parameter pattern: (object_pattern (pair_pattern value: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(required_parameter pattern: (object_pattern (pair_pattern value: (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (object_pattern (pair_pattern value: (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (object_pattern (pair_pattern value: (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (object_pattern (pair_pattern value: (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (object_pattern (pair_pattern value: (assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (object_pattern (pair_pattern value: (assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (object_pattern (pair_pattern value: (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (object_pattern (pair_pattern value: (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (object_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(optional_parameter pattern: (object_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(required_parameter pattern: (object_pattern (rest_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (object_pattern (rest_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (object_pattern (rest_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (object_pattern (rest_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))
(optional_parameter pattern: (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))
(required_parameter pattern: (array_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter))))
(optional_parameter pattern: (array_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter))))
(required_parameter pattern: (array_pattern (object_pattern (object_assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (object_pattern (object_assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (object_pattern (pair_pattern value: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (object_pattern (pair_pattern value: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (object_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (object_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(optional_parameter pattern: (array_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(required_parameter pattern: (array_pattern (array_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (array_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (array_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (array_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (array_pattern (assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (array_pattern (assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (array_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (array_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(optional_parameter pattern: (array_pattern (assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(required_parameter pattern: (array_pattern (assignment_pattern left: (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (assignment_pattern left: (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (assignment_pattern left: (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (assignment_pattern left: (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (assignment_pattern left: (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (assignment_pattern left: (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(optional_parameter pattern: (array_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(required_parameter pattern: (array_pattern (rest_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (rest_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (array_pattern (rest_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (array_pattern (rest_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))
(optional_parameter pattern: (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))
(required_parameter pattern: (rest_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter))))
(optional_parameter pattern: (rest_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter))))
(required_parameter pattern: (rest_pattern (object_pattern (object_assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (rest_pattern (object_pattern (object_assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (rest_pattern (object_pattern (pair_pattern value: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (rest_pattern (object_pattern (pair_pattern value: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (rest_pattern (object_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (rest_pattern (object_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (rest_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(optional_parameter pattern: (rest_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter))))
(required_parameter pattern: (rest_pattern (array_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (rest_pattern (array_pattern (object_pattern (object_assignment_pattern left: (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (rest_pattern (array_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (rest_pattern (array_pattern (array_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (rest_pattern (array_pattern (assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (rest_pattern (array_pattern (assignment_pattern left: (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(required_parameter pattern: (rest_pattern (array_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))
(optional_parameter pattern: (rest_pattern (array_pattern (rest_pattern (object_pattern (shorthand_property_identifier_pattern) @variable.parameter)))))

; JSX rules; rule IDs map to sources in README.md.
; Lowercase and namespaced tags denote intrinsic elements; other names are components.

; J01-J03: MIT highlights-jsx.scm adapted to grammar name fields and capture vocabulary.
((jsx_opening_element name: (identifier) @tag.jsx) (#match? @tag.jsx "^[a-z]"))
((jsx_closing_element name: (identifier) @tag.jsx) (#match? @tag.jsx "^[a-z]"))
((jsx_self_closing_element name: (identifier) @tag.jsx) (#match? @tag.jsx "^[a-z]"))

; J04-J06: component names, including member paths.
(jsx_opening_element name: [(identifier) (member_expression)] @tag.component.jsx
  (#not-match? @tag.component.jsx "^[a-z][^.]*$"))
(jsx_closing_element name: [(identifier) (member_expression)] @tag.component.jsx
  (#not-match? @tag.component.jsx "^[a-z][^.]*$"))
(jsx_self_closing_element name: [(identifier) (member_expression)] @tag.component.jsx
  (#not-match? @tag.component.jsx "^[a-z][^.]*$"))

; J07, J09: grammar-derived namespaces; J08 adapts MIT highlights-jsx.scm attributes.
[(jsx_opening_element name: (jsx_namespace_name) @tag.jsx)
 (jsx_closing_element name: (jsx_namespace_name) @tag.jsx)
 (jsx_self_closing_element name: (jsx_namespace_name) @tag.jsx)]
(jsx_attribute [(property_identifier) (jsx_namespace_name)] @attribute.jsx)
(jsx_namespace_name ":" @punctuation.delimiter.jsx)

; J10-J12: MIT highlights-jsx.scm adapted to JSX-specific captures; J13: grammar-derived.
(jsx_opening_element ["<" ">"] @punctuation.bracket.jsx)
(jsx_closing_element ["</" ">"] @punctuation.bracket.jsx)
(jsx_self_closing_element ["<" "/>"] @punctuation.bracket.jsx)
(jsx_expression "{" @punctuation.special "}" @punctuation.special) @embedded

; J14-J16: literal JSX text, entities and comments.
(jsx_text) @text.jsx
(html_character_reference) @string.special
(html_comment) @comment
