// Command genkeywords builds the self-contained TypeScript-family queries.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

const grammarRef = "e2c53597d6a5"

// maxParameterPatternDepth limits T27 to four binding-pattern nodes between
// a parameter and its shorthand binding, counting object, array, pair-value,
// assignment (including object defaults), and rest nodes together. Deeper
// shorthand bindings keep only their ordinary variable capture.
const maxParameterPatternDepth = 4

var grammarHashes = map[string]string{
	"typescript": "2895e931ca9f4d8b7352bf6878fd7805fff36428882cf8be85ccfaf4152aafbd",
	"tsx":        "1e0fa3879c32bf155d4883944d6c4cb87625c77bc8f4d674484c45194ed45745",
}

const header = `; Generated by go run ./cmd/genkeywords; do not edit.
; Original structural rules and token classifications: queries/*.scm, queries/tokens.json.
; MIT upstream sources used:
; tree-sitter/tree-sitter-javascript@v0.25.0/queries/highlights.scm
; tree-sitter/tree-sitter-javascript@v0.25.0/queries/highlights-jsx.scm
;   Copyright (c) 2014 Max Brunsfeld; licenses/tree-sitter-javascript/LICENSE
; zed-industries/tree-sitter-typescript@e2c53597d6a5/queries/highlights.scm
;   Copyright (c) 2017 Max Brunsfeld; licenses/tree-sitter-typescript/LICENSE
; Original additions are covered by this repository's LICENSE.

`

type tokenRule struct {
	Capture string `json:"capture"`
	Reason  string `json:"reason"`
}

type nodeType struct {
	Type  string `json:"type"`
	Named bool   `json:"named"`
}

func main() {
	check := flag.Bool("check", false, "report stale output without writing")
	list := flag.Bool("list", false, "list every anonymous token and its classification without writing")
	grammarDir := flag.String("grammar-dir", "", "read <language>-node-types.json from this directory instead of HTTPS (hashes still verified)")
	flag.Parse()
	if err := run(*check, *list, *grammarDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(check, list bool, grammarDir string) error {
	data, err := os.ReadFile("queries/tokens.json")
	if err != nil {
		return err
	}
	var table map[string]tokenRule
	if err := json.Unmarshal(data, &table); err != nil {
		return err
	}
	vocabulary := strings.Fields("attribute.jsx boolean comment constant constant.builtin constructor embedded function function.method keyword keyword.control keyword.declaration keyword.import keyword.operator.regex nested number operator property property.name punctuation.bracket punctuation.bracket.jsx punctuation.delimiter punctuation.delimiter.jsx punctuation.special string string.escape string.regex string.special tag.component.jsx tag.jsx text.jsx type type.builtin type.class type.name variable variable.parameter variable.special")
	allowed := make(map[string]bool, len(vocabulary))
	for _, capture := range vocabulary {
		allowed[capture] = true
	}
	for token, rule := range table {
		if (rule.Capture == "") == (rule.Reason == "") || (rule.Capture != "" && !allowed[rule.Capture]) {
			return fmt.Errorf("token %q needs exactly one valid capture or reason", token)
		}
	}
	seen := make(map[string]bool)
	tokens := make(map[string][]string)
	for _, language := range []string{"typescript", "tsx"} {
		data, err := grammar(language, grammarDir)
		if err != nil {
			return err
		}
		var nodes []nodeType
		if err := json.Unmarshal(data, &nodes); err != nil {
			return err
		}
		for _, node := range nodes {
			if node.Named {
				continue
			}
			if _, ok := table[node.Type]; !ok {
				return fmt.Errorf("%s: anonymous token %q has no classification", language, node.Type)
			}
			seen[node.Type] = true
			tokens[language] = append(tokens[language], node.Type)
		}
		sort.Strings(tokens[language])
	}
	for token := range table {
		if !seen[token] {
			return fmt.Errorf("classification for nonexistent anonymous token %q", token)
		}
	}
	if list {
		for _, language := range []string{"typescript", "tsx"} {
			for _, token := range tokens[language] {
				rule := table[token]
				if rule.Capture != "" {
					fmt.Printf("%s %q @%s\n", language, token, rule.Capture)
				} else {
					fmt.Printf("%s %q none: %s\n", language, token, rule.Reason)
				}
			}
		}
		return nil
	}
	fragments := make(map[string][]byte, 3)
	for _, part := range []string{"common", "typescript", "jsx"} {
		fragment, err := os.ReadFile(filepath.Join("queries", part+".scm"))
		if err != nil {
			return err
		}
		fragments[part] = fragment
	}
	var parameterPatterns bytes.Buffer
	writeParameterPatterns(&parameterPatterns)
	fragments["typescript"] = append(fragments["typescript"], parameterPatterns.Bytes()...)
	status := "generated"
	if check {
		status = "current"
	}
	for _, language := range []string{"typescript", "tsx"} {
		var out bytes.Buffer
		out.WriteString(header)
		out.WriteString("; Anonymous tokens, in lexical order; provenance: pinned node-types.json.\n")
		for _, token := range tokens[language] {
			rule := table[token]
			if rule.Capture != "" {
				fmt.Fprintf(&out, "%s @%s\n", strconv.Quote(token), rule.Capture)
			}
		}
		parts := []string{"common", "typescript"}
		if language == "tsx" {
			parts = append(parts, "jsx")
		}
		for _, part := range parts {
			fragment := fragments[part]
			out.WriteByte('\n')
			out.Write(fragment)
		}
		targets := []string{language}
		if language == "tsx" {
			targets = append(targets, "javascript")
		}
		for _, target := range targets {
			path := filepath.Join(target, "queries", "highlights.scm")
			if check {
				old, err := os.ReadFile(path)
				if err != nil || !bytes.Equal(old, out.Bytes()) {
					return fmt.Errorf("%s is stale; run go run ./cmd/genkeywords", path)
				}
			} else {
				if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
					return err
				}
				if err := os.WriteFile(path, out.Bytes(), 0644); err != nil {
					return err
				}
			}
			fmt.Printf("%s: %d anonymous tokens classified; %s\n", target, len(tokens[language]), status)
		}
	}
	return nil
}

// writeParameterPatterns follows only binding edges from the pinned grammar.
// In particular, defaults' right sides and computed property keys are expressions,
// not parameter bindings. Tree-sitter queries cannot express unbounded ancestry.
func writeParameterPatterns(out *bytes.Buffer) {
	type pattern struct {
		node      string
		field     string
		children  []string
		shorthand bool
	}
	graph := map[string]pattern{
		"object_pattern":            {"object_pattern", "", []string{"object_assignment_pattern", "pair_pattern", "rest_pattern"}, true},
		"array_pattern":             {"array_pattern", "", []string{"object_pattern", "array_pattern", "assignment_pattern", "rest_pattern"}, false},
		"pair_pattern":              {"pair_pattern", "value", []string{"object_pattern", "array_pattern", "assignment_pattern", "rest_pattern"}, false},
		"assignment_pattern":        {"assignment_pattern", "left", []string{"object_pattern", "array_pattern", "rest_pattern"}, false},
		"object_assignment_pattern": {"object_assignment_pattern", "left", []string{"object_pattern", "array_pattern"}, true},
		"rest_pattern":              {"rest_pattern", "", []string{"object_pattern", "array_pattern"}, false},
	}
	fmt.Fprintf(out, "\n; T27: grammar-derived shorthand parameter bindings, at most %d pattern nodes.\n", maxParameterPatternDepth)
	path := make([]pattern, 0, maxParameterPatternDepth)
	var visit func(string)
	visit = func(node string) {
		step := graph[node]
		path = append(path, step)
		if step.shorthand {
			for _, parameter := range []string{"required_parameter", "optional_parameter"} {
				fmt.Fprintf(out, "(%s pattern: ", parameter)
				for _, ancestor := range path {
					fmt.Fprintf(out, "(%s ", ancestor.node)
					if ancestor.field != "" {
						fmt.Fprintf(out, "%s: ", ancestor.field)
					}
				}
				out.WriteString("(shorthand_property_identifier_pattern) @variable.parameter")
				for range len(path) + 1 {
					out.WriteByte(')')
				}
				out.WriteByte('\n')
			}
		}
		if len(path) < maxParameterPatternDepth {
			for _, child := range step.children {
				visit(child)
			}
		}
		path = path[:len(path)-1]
	}
	for _, root := range []string{"object_pattern", "array_pattern", "rest_pattern"} {
		visit(root)
	}
}

func grammar(language, dir string) ([]byte, error) {
	var data []byte
	var err error
	if dir != "" {
		data, err = os.ReadFile(filepath.Join(dir, language+"-node-types.json"))
	} else {
		client := &http.Client{Timeout: 30 * time.Second}
		url := "https://raw.githubusercontent.com/zed-industries/tree-sitter-typescript/" + grammarRef + "/" + language + "/src/node-types.json"
		var resp *http.Response
		resp, err = client.Get(url)
		if err != nil {
			return nil, err
		}
		defer resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("%s: HTTP %s", url, resp.Status)
		}
		data, err = io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	}
	if err != nil {
		return nil, err
	}
	if got := fmt.Sprintf("%x", sha256.Sum256(data)); got != grammarHashes[language] {
		return nil, fmt.Errorf("%s node-types.json checksum mismatch: %s", language, got)
	}
	return data, nil
}
